# Generated by Django 4.1.7 on 2023-04-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_familyweeklyschedule_weektwo_weekthree_weekone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekfour',
            name='username',
        ),
        migrations.RemoveField(
            model_name='weekone',
            name='username',
        ),
        migrations.RemoveField(
            model_name='weekthree',
            name='username',
        ),
        migrations.RemoveField(
            model_name='weektwo',
            name='username',
        ),
    ]
