# Generated by Django 4.1.7 on 2023-04-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_weekfour_username_remove_weekone_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FamilyWeeklySchedule',
            new_name='FamilyMemberWeeklySchedule',
        ),
    ]
