# Generated by Django 4.1.7 on 2023-04-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_familyweeklyschedule_familymemberweeklyschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='customuser',
            name='additional_medic_info',
            field=models.CharField(blank=True, help_text='please specify', max_length=100, null=True, verbose_name='Any Chronic Ailment'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blood_group',
            field=models.CharField(choices=[('-', 'Unknown'), ('aa', 'AA'), ('bb', 'BB'), ('cc', 'CC')], default='-', max_length=10, verbose_name='Blood Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='cloth_size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cloth Size'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='course_of_study',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course of Study'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_year_of_study',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current Year of Study'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='final_year_status',
            field=models.CharField(blank=True, help_text='Update when appropriate', max_length=20, null=True, verbose_name='Final Year Status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='genotype',
            field=models.CharField(choices=[('-', 'Unknown'), ('aa', 'AA'), ('bb', 'BB'), ('cc', 'CC')], default='-', max_length=10, verbose_name='Genotype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shoe Size'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='years_of_study',
            field=models.IntegerField(blank=True, null=True, verbose_name='No of Years of Study'),
        ),
    ]
