# Generated by Django 4.1.7 on 2023-04-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_sex_customuser_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='additional_medic_info',
            new_name='chronic_illness',
        ),
    ]
