# Generated by Django 4.1.7 on 2023-04-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_additional_medic_info_customuser_chronic_illness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='shepherd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shepherd'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_shepherd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subshepherd'),
        ),
    ]
