# Generated by Django 4.1.7 on 2023-04-24 14:51

from django.db import migrations, models
import users.my_models.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_shepherd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subshepherd',
            name='shepherd',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='blood_group',
            field=models.CharField(choices=[('-', 'Unknown'), ('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+')], max_length=10, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='genotype',
            field=models.CharField(choices=[('-', 'Unknown'), ('AA', 'AA'), ('AB', 'AB'), ('AS', 'AS'), ('SS', 'SS')], max_length=10, verbose_name='Genotype'),
        ),
        migrations.AlterField(
            model_name='subshepherd',
            name='date_of_appointment',
            field=models.DateField(validators=[users.my_models.utilities.Validators.validate_prevent_future_date]),
        ),
    ]
