# Generated by Django 4.2.1 on 2023-05-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_last_active_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('new_mem', 'New Member'), ('mem', 'Member'), ('worker', 'Worker'), ('sub_shep', 'Sub Shepherd'), ('core_shep', 'Core Shepherd'), ('chief_shep', 'Chief Shepherd')], default='new_mem', max_length=15, verbose_name='Level'),
        ),
    ]
