# Generated by Django 4.2.1 on 2023-05-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_shepherd',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='is_subshepherd',
        ),
    ]
