# Generated by Django 4.1.7 on 2023-03-26 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evangelism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_visit', models.CharField(max_length=300)),
                ('hours_spent_per_week', models.PositiveIntegerField(default=0)),
                ('no_led_to_christ', models.PositiveIntegerField(default=0)),
                ('follow_up', models.PositiveIntegerField(default=0)),
                ('invitees', models.PositiveIntegerField(default=0)),
                ('holy_spirit_baptism', models.PositiveIntegerField(default=0)),
                ('no_of_people_prayed', models.PositiveIntegerField(default=0)),
                ('prints_shared', models.PositiveIntegerField(default=0)),
                ('messages', models.TextField()),
                ('snippets', models.PositiveIntegerField(default=0)),
                ('first_date_of_week', models.DateField(default=django.utils.timezone.now)),
                ('last_date_of_week', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-no_led_to_christ',),
            },
        ),
    ]
