# Generated by Django 4.1.7 on 2023-03-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('prayer_marathon', 'Prayer Marathon'), ('bible_reading', 'Bible Reading'), ('church_work', 'Church Work'), ('evangelism', 'Evangelism'), ('prophetic_vision', 'Prophetic Vision'), ('bio_data', 'Bio Data')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Recent Activities',
                'ordering': ('-date',),
            },
        ),
    ]
