# Generated by Django 4.1.7 on 2023-03-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_development', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayermarathon',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='prayermarathon',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='prayermarathon',
            name='status',
        ),
    ]
